-- MySQL Script generated by MySQL Workbench
-- Monday 25 March 2019 12:10:19 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema abc_bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema abc_bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `abc_bank` ;
USE `abc_bank` ;

-- -----------------------------------------------------
-- Table `abc_bank`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `address_id` INT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_customer_address_idx` (`address_id` ASC),
  CONSTRAINT `fk_customer_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `abc_bank`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`branch` (
  `branch_id` INT NOT NULL AUTO_INCREMENT,
  `branch_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`branch_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`token_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`token_type` (
  `token_type_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`token_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`token` (
  `token_id` INT NOT NULL AUTO_INCREMENT,
  `token_type_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `customer_id` INT NULL,
  `comment` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `token_priority` ENUM('REGULAR', 'PREMIUM') NULL,
  PRIMARY KEY (`token_id`),
  INDEX `fk_token_1_idx` (`token_type_id` ASC),
  INDEX `fk_token_branch_idx` (`branch_id` ASC),
  INDEX `fk_token_customer_idx` (`customer_id` ASC),
  CONSTRAINT `fk_token_type`
    FOREIGN KEY (`token_type_id`)
    REFERENCES `abc_bank`.`token_type` (`token_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_token_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `abc_bank`.`branch` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_token_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `abc_bank`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`counter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`counter` (
  `counter_id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NOT NULL,
  `employee_id` INT NULL,
  `counter_type` ENUM('REGULAR', 'PREMIUM', 'BOTH') NOT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`counter_id`),
  INDEX `fk_counter_branch_idx` (`branch_id` ASC),
  INDEX `fk_counter_emp_idx` (`employee_id` ASC),
  CONSTRAINT `fk_counter_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `abc_bank`.`branch` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_counter_emp`
    FOREIGN KEY (`employee_id`)
    REFERENCES `abc_bank`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`service` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`counter_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`counter_service` (
  `counter_service_id` INT NOT NULL AUTO_INCREMENT,
  `counter_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  PRIMARY KEY (`counter_service_id`),
  INDEX `fk_counter_service_1_idx` (`counter_id` ASC),
  INDEX `fk_counter_service_1_idx1` (`service_id` ASC),
  CONSTRAINT `fk_counter_service_counter`
    FOREIGN KEY (`counter_id`)
    REFERENCES `abc_bank`.`counter` (`counter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_counter_service_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `abc_bank`.`service` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`token_sub_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`token_sub_task` (
  `token_sub_task_id` INT NOT NULL AUTO_INCREMENT,
  `token_type_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  PRIMARY KEY (`token_sub_task_id`),
  INDEX `fk_token_sub_task_1_idx` (`token_type_id` ASC),
  INDEX `fk_token_sub_task_1_idx1` (`service_id` ASC),
  CONSTRAINT `fk_token_sub_task_token_type`
    FOREIGN KEY (`token_type_id`)
    REFERENCES `abc_bank`.`token_type` (`token_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_token_sub_task_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `abc_bank`.`service` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`token_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`token_status` (
  `token_status_id` INT NOT NULL AUTO_INCREMENT,
  `token_id` INT NOT NULL,
  `counter_id` INT NOT NULL,
  `in_progress` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`token_status_id`),
  INDEX `fk_token_status_1_idx` (`token_id` ASC),
  INDEX `fk_token_status_1_idx1` (`counter_id` ASC),
  CONSTRAINT `fk_token_status_token`
    FOREIGN KEY (`token_id`)
    REFERENCES `abc_bank`.`token` (`token_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_token_status_counter`
    FOREIGN KEY (`counter_id`)
    REFERENCES `abc_bank`.`counter` (`counter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abc_bank`.`employee_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abc_bank`.`employee_role` (
  `employee_role_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`employee_role_id`),
  INDEX `fk_employee_role_1_idx` (`role_id` ASC),
  INDEX `fk_role_emp_idx` (`employee_id` ASC),
  CONSTRAINT `fk_emp_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `abc_bank`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_emp`
    FOREIGN KEY (`employee_id`)
    REFERENCES `abc_bank`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;