package com.turvo.bankingqueue.entity;
// Generated 21 Mar, 2019 3:04:51 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "branch", catalog = "abc_bank")
public class Branch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer branchId;
	private String branchName;
	private Set<Counter> counters = new HashSet<Counter>(0);
	private Set<Token> tokens = new HashSet<Token>(0);

	public Branch() {
	}

	public Branch(String branchName) {
		this.branchName = branchName;
	}

	public Branch(String branchName, Set<Counter> counters, Set<Token> tokens) {
		this.branchName = branchName;
		this.counters = counters;
		this.tokens = tokens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "branch_id", unique = true, nullable = false)
	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	@Column(name = "branch_name", nullable = false, length = 45)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<Counter> getCounters() {
		return this.counters;
	}

	public void setCounters(Set<Counter> counters) {
		this.counters = counters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<Token> getTokens() {
		return this.tokens;
	}

	public void setTokens(Set<Token> tokens) {
		this.tokens = tokens;
	}

}
