package com.turvo.bankingqueue.entity;
// Generated 21 Mar, 2019 3:04:51 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Counter generated by hbm2java
 */
@Entity
@Table(name = "counter", catalog = "abc_bank")
public class Counter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer counterId;
	private Branch branch;
	private Employee employee;
	private String counterType;
	private String active;
	private Set<TokenStatus> tokenStatuses = new HashSet<TokenStatus>(0);
	private Set<CounterService> counterServices = new HashSet<CounterService>(0);

	public Counter() {
	}

	public Counter(Branch branch) {
		this.branch = branch;
	}

	public Counter(Branch branch, Employee employee, String counterType, String active, Set<TokenStatus> tokenStatuses,
			Set<CounterService> counterServices) {
		this.branch = branch;
		this.employee = employee;
		this.counterType = counterType;
		this.active = active;
		this.tokenStatuses = tokenStatuses;
		this.counterServices = counterServices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "counter_id", unique = true, nullable = false)
	public Integer getCounterId() {
		return this.counterId;
	}

	public void setCounterId(Integer counterId) {
		this.counterId = counterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "counter_type", length = 45)
	public String getCounterType() {
		return this.counterType;
	}

	public void setCounterType(String counterType) {
		this.counterType = counterType;
	}

	@Column(name = "active", length = 8)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "counter")
	public Set<TokenStatus> getTokenStatuses() {
		return this.tokenStatuses;
	}

	public void setTokenStatuses(Set<TokenStatus> tokenStatuses) {
		this.tokenStatuses = tokenStatuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "counter")
	public Set<CounterService> getCounterServices() {
		return this.counterServices;
	}

	public void setCounterServices(Set<CounterService> counterServices) {
		this.counterServices = counterServices;
	}

}
