package com.turvo.bankingqueue.entity;
// Generated 21 Mar, 2019 3:04:51 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TokenStatus generated by hbm2java
 */
@Entity
@Table(name = "token_status", catalog = "abc_bank")
public class TokenStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer tokenStatusId;
	private Counter counter;
	private Token token;
	private Boolean inProgress;

	public TokenStatus() {
	}

	public TokenStatus(Counter counter, Token token) {
		this.counter = counter;
		this.token = token;
	}

	public TokenStatus(Counter counter, Token token, Boolean inProgress) {
		this.counter = counter;
		this.token = token;
		this.inProgress = inProgress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "token_status_id", unique = true, nullable = false)
	public Integer getTokenStatusId() {
		return this.tokenStatusId;
	}

	public void setTokenStatusId(Integer tokenStatusId) {
		this.tokenStatusId = tokenStatusId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "counter_id", nullable = false)
	public Counter getCounter() {
		return this.counter;
	}

	public void setCounter(Counter counter) {
		this.counter = counter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "token_id", nullable = false)
	public Token getToken() {
		return this.token;
	}

	public void setToken(Token token) {
		this.token = token;
	}

	@Column(name = "in_progress")
	public Boolean getInProgress() {
		return this.inProgress;
	}

	public void setInProgress(Boolean inProgress) {
		this.inProgress = inProgress;
	}

}
