package com.turvo.bankingqueue.entity;
// Generated 21 Mar, 2019 3:04:51 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TokenSubTask generated by hbm2java
 */
@Entity
@Table(name = "token_sub_task", catalog = "abc_bank")
public class TokenSubTask implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer tokenSubTaskId;
	private Service service;
	private TokenType tokenType;

	public TokenSubTask() {
	}

	public TokenSubTask(Service service, TokenType tokenType) {
		this.service = service;
		this.tokenType = tokenType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "token_sub_task_id", unique = true, nullable = false)
	public Integer getTokenSubTaskId() {
		return this.tokenSubTaskId;
	}

	public void setTokenSubTaskId(Integer tokenSubTaskId) {
		this.tokenSubTaskId = tokenSubTaskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_id", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "token_type_id", nullable = false)
	public TokenType getTokenType() {
		return this.tokenType;
	}

	public void setTokenType(TokenType tokenType) {
		this.tokenType = tokenType;
	}

}
